services:
  db:
    image: quay.io/minio/minio:RELEASE.2025-02-28T09-55-16Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio-root-user
      MINIO_ROOT_PASSWORD: minio-root-password
    volumes:
      - ./.minio-data:/data
    command: server /data --console-address ":9001"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 3001:3001
    environment:
      NODE_ENV: 'production'
      PORT: '3001'
    command:
      - npm
      - run
      - start
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VITE_API_URL: 'http://localhost:3001'
    ports:
      - 3000:3000
    command:
      - serve
      - -s
      - dist
      - -p
      - '3000'
