FROM node:20-alpine AS builder
ARG VITE_API_URL=http://localhost:3001

WORKDIR /app

COPY client client
COPY types types

ENV VITE_API_URL="${VITE_API_URL}"
RUN cd client && npm install && npm run build

FROM node:20-alpine AS runner
WORKDIR /app
RUN npm i -g serve

COPY --from=builder /app/client/dist dist

